### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by FirefoxSurvivor** [EtiTheSpirit/WEMConverter#3]
Hello!

Please, can you explain how to run this program? I would need to convert some WEM file into WAV.

Thanks in advance

**Comment by XanTheDragon** [comment]
Apologies for the month late response.

Have you even opened the EXE file? Attempting to open the EXE file will show you exactly how to use it.

**Comment by EtiTheSpirit** [comment]
I'm closing this issue since you seem to have nothing else to add to it ~~and it's been a year. Whoops.~~

**Comment by AsrielDewitt** [comment]
Sorry for opening this back, but how do you go from Wave file or OGG file back to WEM?
