### ISSUE TITLE
Can not convert wem to wav

### ISSUE THREAD

**Issue by XiTongWu** [EtiTheSpirit/WEMConverter#4]
I tried to drag the wem file onto the exe, but nothing happened. Then, I tried to use powershell to run exe with option, it mentioned that " wem convert to wav is a little bit broken right now. "  It success to convert it, Athough what converted is just noise.
I used it to convert Monster Hunter World : iceborn file
Can you give me some advise?

**Comment by XiTongWu** [comment]
Oh, In Monster Hunter World: Iceborn, the wem file was packed as npck

**Comment by XanTheDragon** [comment]
It's likely picking up on the wrong format. The program was mainly designed for No Man's Sky where WEM files are either in WAV or OGG format, nothing else. Any games that use alternative formats will cause unexpected results.

**Comment by XiTongWu** [comment]
OK，thanks for your answer，I try to find something else which useful

**Comment by EtiTheSpirit** [comment]
I'm closing this issue since you've got nothing else to add by the looks of things.
