### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by goshante** [EtiTheSpirit/WEMConverter#7]
All wem -> wav are broken and just a noise.
All wav -> wem with truncated chunks.
It just useless.

**Comment by EtiTheSpirit** [comment]
Adding invalid for now.

While I am sorry to hear that it's not working for you, simply throwing it at me and saying "look it's broken" is worse than useless. Let's start with the most important question: *What* is broken? You need to actually give me file examples so we can figure out why this happens. As far as I and many others are concerned, it does work, so this is definitely an edge case.
