### ISSUE TITLE
Converting wav files to WEM produces static in Metal Gear Solid V: The Phantom Pain

### ISSUE THREAD

**Issue by countfuzzball** [EtiTheSpirit/WEMConverter#8]
I'm trying to get wav files into Metal Gear Solid V: The Phantom Pain as wem files, but all the converted sounds are played back as ear-shattering static when in the game. 

I'm using Ravioli Explorer to preview and extract the wem files to wav.
This happens even with the vanilla files. I've uploaded a number of files for your convenience:

RIFF_0041.wem: Original wem file. This file is reported as being a standard stereo PCM wav file at 41000hz sample rate.
File0001.wav: The extracted wem file.
File0001.wav.wem: The converted wav file using WEMConverter.

https://drive.google.com/drive/folders/1cNQYpry0ifoNbEmKZsne6cpAKMTa3u1q?usp=sharing

Just to note, the converted wem files do playback fine in Ravioli, just once they're played back by the game's audio engine it's nothing but static noise.

Cheers!

**Comment by EtiTheSpirit** [comment]
This may not be related to this software as far as I can tell, especially considering that other tools play it properly. MGSV may be forcefully loading them in a different format that causes it to not play properly (which, while it is a violation of WEM's standards to do so, is possible).

I don't think there's much that can be done here. Sorry.
